# Server settings
# Use the simple server factory if you only want to run on a single port
# HEROKU NOTE - the port gets be overridden with the Heroku $PORT in the Procfile
server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 9090

# Database settings
# HEROKU NOTE - none of these are used since the values come from the Heroku $DATABASE_URL
database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost/fantastix
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

swagger:
  resourcePackage: edu.neu.cs5500.fantastix.resources
  

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  # Logger-specific levels.
  loggers:
    # Sets the level for 'com.example.app' to DEBUG.
    com.example.app: DEBUG
    org.hibernate.SQL: ALL
  appenders:
    - type: console